# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ce96bc1af395c76cb15ac9d123aa4ac39c1ffe24c631358d3d3f2d09a21595f058b8b500ca5595d5378675b84384dc15ed698d727dcd4a74582418661b09535

test:
  secret_key_base: 6c2f75d9554c87d811cfcdac97f027b83141e6f6902b6ef319164bbef5baef996beda2c1ed260d3713a7516370f324bb5195b9465d810c2845ea3133ab7fde03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
